Play travis
Otus-DevOps-2018-11/madsiberian_infra pull request #1
Opened 2019-01-15 16:32 UTC by madsiberian

# Выполнено ДЗ № 2

 - [Х] Основное ДЗ
 - [ ] Задание со *

 ## В процессе сделано:
 - Добавлен шаблон ПР
 - Добавлена конфигурация travis
 - Добавлен и исправлен test.py

 ## PR checklist
 - [ ] Выставил label с номером домашнего задания
 - [X] Выставил label с темой домашнего задания

2019-01-15 20:11 UTC, mrgreyves requested changes
Здравствуйте!) Заполните пожалуйста пуллреквест!)

2019-01-16 15:34 UTC, madsiberian commented
> Здравствуйте!) Заполните пожалуйста пуллреквест!)

Позвольте возразить: в задании сказано, что шаблон будет работать начиная со следующего ДЗ, а не текущего.

2019-01-16 17:00 UTC, mrgreyves commented
Отчасти я с вами согласен, но все же хотя бы минимальное заполнение пуллреквеста является хорошей практикой.

2019-01-16 17:18 UTC, mrgreyves approved these changes
up!

2019-01-16 17:51 UTC, merged

2019-01-16 17:52 UTC, madsiberian commented
> Отчасти я с вами согласен, но все же хотя бы минимальное заполнение пуллреквеста является хорошей практикой.

Готово